import * as AST from "../wgsl_ast.js";
import { Data } from "./data.js";
import { ExecContext } from "./exec_context.js";
import { ExecInterface } from "./exec_interface.js";
import { TypeInfo } from "../wgsl_reflect.js";
export declare class BuiltinFunctions {
    exec: ExecInterface;
    constructor(exec: ExecInterface);
    getTypeInfo(type: string): TypeInfo | null;
    All(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Any(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Select(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    ArrayLength(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Abs(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Acos(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Acosh(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Asin(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Asinh(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Atan(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Atanh(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Atan2(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Ceil(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    _clamp(value: number, min: number, max: number): number;
    Clamp(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Cos(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Cosh(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    CountLeadingZeros(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    _countOneBits(value: number): number;
    CountOneBits(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    _countTrailingZeros(value: number): number;
    CountTrailingZeros(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Cross(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Degrees(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Determinant(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Distance(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    _dot(e1: number[], e2: number[]): number;
    Dot(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Dot4U8Packed(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Dot4I8Packed(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Exp(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Exp2(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    ExtractBits(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    FaceForward(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    FirstLeadingBit(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    FirstTrailingBit(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Floor(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Fma(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Fract(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Frexp(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    InsertBits(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    InverseSqrt(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Ldexp(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Length(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Log(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Log2(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Max(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Min(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Mix(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Modf(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Normalize(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pow(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    QuantizeToF16(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Radians(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Reflect(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Refract(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    ReverseBits(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Round(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Saturate(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Sign(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Sin(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Sinh(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    _smoothstep(edge0: number, edge1: number, x: number): number;
    SmoothStep(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Sqrt(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Step(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Tan(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Tanh(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    _getTransposeType(t: TypeInfo): TypeInfo;
    Transpose(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Trunc(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Dpdx(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    DpdxCoarse(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    DpdxFine(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Dpdy(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    DpdyCoarse(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    DpdyFine(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Fwidth(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    FwidthCoarse(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    FwidthFine(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureDimensions(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureGather(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureGatherCompare(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureLoad(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureNumLayers(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureNumLevels(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureNumSamples(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureSample(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureSampleBias(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureSampleCompare(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureSampleCompareLevel(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureSampleGrad(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureSampleLevel(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureSampleBaseClampToEdge(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureStore(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicLoad(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicStore(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicAdd(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicSub(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicMax(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicMin(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicAnd(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicOr(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicXor(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicExchange(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    AtomicCompareExchangeWeak(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack4x8snorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack4x8unorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack4xI8(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack4xU8(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack4x8Clamp(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack4xU8Clamp(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack2x16snorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack2x16unorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Pack2x16float(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Unpack4x8snorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Unpack4x8unorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Unpack4xI8(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Unpack4xU8(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Unpack2x16snorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Unpack2x16unorm(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    Unpack2x16float(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    StorageBarrier(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    TextureBarrier(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    WorkgroupBarrier(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    WorkgroupUniformLoad(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupAdd(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupExclusiveAdd(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupInclusiveAdd(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupAll(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupAnd(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupAny(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupBallot(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupBroadcast(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupBroadcastFirst(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupElect(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupMax(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupMin(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupMul(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupExclusiveMul(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupInclusiveMul(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupOr(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupShuffle(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupShuffleDown(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupShuffleUp(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupShuffleXor(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    SubgroupXor(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    QuadBroadcast(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    QuadSwapDiagonal(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    QuadSwapX(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
    QuadSwapY(node: AST.CallExpr | AST.Call, context: ExecContext): Data | null;
}
